name: Tests

on:
  push:
    branches:
      - '**'  # すべてのブランチを対象に

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.lock

    - name: Test with pytest
      run: |
        pytest -v
