name: Hello World on Push

on:
  push:
    branches:
      - '**'  # すべてのブランチを対象に

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Say Hello
      run: echo "Hello, World!"
